project_id = "rhoxpfuephkuaartuqou"

[functions.scholar-summary]
verify_jwt = true

[functions.ask]
verify_jwt = true

[functions.ask-public]
verify_jwt = false

[functions.ask-scholar]
verify_jwt = false
