import React, { useState, useEffect } from 'react';
import { NGS_DATA } from '../../scholars-data.js';
import { useLocalStorage } from '../hooks/useLocalStorage.js';
import { loadFromSupabase, loadPendingSubmissions } from '../supabase-loader.js';
import { storedMode, storedRate, persistFx, fetchMarketRate } from '../fx.js';
import { writeExpense, writeSemester, updateExpense, deleteExpense, markActivityRead, approveSubmission, rejectSubmission } from '../supabase-writer.js';
import { supabase } from '../lib/supabase.js';
import { FxCtx } from '../context/FxContext.jsx';
import { DataCtx } from '../context/DataContext.jsx';
import { LockScreen } from '../components/LockScreen.jsx';
import { SectionErrorBoundary } from '../components/SectionErrorBoundary.jsx';
import { NavBar } from '../components/NavBar.jsx';
import { AlertsSection } from '../components/AlertsSection.jsx';
import { StatusSection } from '../components/StatusSection.jsx';
import { ExpenseSection } from '../components/expenses/ExpenseSection.jsx';
import { DeadlinesSection } from '../components/DeadlinesSection.jsx';
import { EnglishSection } from '../components/EnglishSection.jsx';
import { NavigatorAI } from '../components/NavigatorAI.jsx';
import { NavigatorAIDrawer } from '../components/NavigatorAIDrawer.jsx';
import { DocumentsSection } from '../components/DocumentsSection.jsx';
import { CareerSection } from '../components/CareerSection.jsx';
import { RiskSection } from '../components/RiskSection.jsx';
import { GradesSection } from '../components/GradesSection.jsx';
import { NavFooter } from '../components/NavFooter.jsx';

if (!NGS_DATA || !NGS_DATA.config) {
  throw new Error('NGS_DATA missing — hard-refresh (Ctrl/Cmd+Shift+R)');
}

const STATIC_SCHOLAR_KEYS = ['claire', 'april', 'aljane'];
const ALL_SECTION_IDS = ['alerts', 'status', 'expenses', 'deadlines', 'english', 'navigator-ai', 'documents', 'career', 'risk', 'grades'];

export function Navigator() {
  const [D, setD] = useState(NGS_DATA);
  const scholarKeys = STATIC_SCHOLAR_KEYS.filter(k => D.scholars[k]);

  const [unlocked, setUnlocked] = useState(false);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (session) setUnlocked(true);
    });
  }, []);

  const [currency, setCurrency] = useState('PHP');
  const [liveGpa, setLiveGpa]   = useState({});
  const [sheetsStatus, setSheetsStatus] = useState('loading');
  const [refreshKey, setRefreshKey]     = useState(0);

  const [fxMode, setFxMode]     = useState(() => storedMode());
  const [fxRate, setFxRate]     = useState(() => storedRate());
  const [fxStatus, setFxStatus] = useState('idle');

  const [writeError, setWriteError] = useState(false);

  // Activity feed — edits/delete requests from entry.html
  const [activityFeed, setActivityFeed] = useState([]);
  // Pending expense submissions awaiting approval
  const [pendingSubmissions, setPendingSubmissions] = useState([]);
  // System alerts from DB (auto-generated by triggers, e.g. GPA risk)
  const [dbAlerts, setDbAlerts] = useState([]);

  useEffect(() => {
    if (!writeError) return;
    const t = setTimeout(() => setWriteError(false), 5000);
    return () => clearTimeout(t);
  }, [writeError]);

  // Load activity + pending submissions on unlock, subscribe to realtime.
  useEffect(() => {
    if (!unlocked) return;

    supabase.from('activity_log').select('*').eq('read', false)
      .order('created_at', { ascending: false })
      .then(({ data }) => setActivityFeed(data || []));

    loadPendingSubmissions()
      .then(setPendingSubmissions)
      .catch(err => console.warn('loadPendingSubmissions failed:', err.message));

    // DB system alerts (GPA risk, etc.)
    supabase.from('alerts').select('*').order('severity')
      .then(({ data }) => setDbAlerts(data || []));

    function reloadAlerts() {
      supabase.from('alerts').select('*').order('severity')
        .then(({ data }) => setDbAlerts(data || []));
    }

    const alertsChannel = supabase.channel('ngs_db_alerts')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'alerts' }, reloadAlerts)
      .subscribe();

    const actChannel = supabase.channel('ngs_activity')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'activity_log' }, payload => {
        setActivityFeed(prev => [payload.new, ...prev]);
      })
      .subscribe();

    const subChannel = supabase.channel('ngs_submissions')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'expense_submissions' }, payload => {
        if (payload.new.status === 'pending') setPendingSubmissions(prev => [payload.new, ...prev]);
      })
      .subscribe();

    const expChannel = supabase.channel('ngs_expenses')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'expenses' }, ({ new: e }) => {
        if (!e?.scholar || !e?.sem) return;
        const row = { id: e.id, item: e.item, amount: parseFloat(e.amount) || 0, qty: parseFloat(e.qty) || 1, cat: e.cat, date: e.date, sent: e.sent, avb: e.avb, vendor: e.vendor || '', sem: e.sem, group_id: e.group_id || null };
        setD(prev => {
          const sd = prev.scholars[e.scholar];
          if (!sd) return prev;
          const semList = sd.expenses?.[e.sem] || [];
          if (semList.some(ex => String(ex.id) === String(e.id))) return prev;
          return { ...prev, scholars: { ...prev.scholars, [e.scholar]: { ...sd, expenses: { ...(sd.expenses || {}), [e.sem]: [...semList, row] } } } };
        });
      })
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'expenses' }, ({ new: e }) => {
        if (!e?.scholar) return;
        setD(prev => {
          const sd = prev.scholars[e.scholar];
          if (!sd) return prev;
          const newExp = {};
          Object.entries(sd.expenses || {}).forEach(([sem, list]) => {
            newExp[sem] = list.map(ex => String(ex.id) === String(e.id)
              ? { ...ex, item: e.item, amount: parseFloat(e.amount) || 0, qty: parseFloat(e.qty) || 1, cat: e.cat, date: e.date, sent: e.sent, avb: e.avb, vendor: e.vendor || '', sem: e.sem, group_id: e.group_id || null }
              : ex);
          });
          return { ...prev, scholars: { ...prev.scholars, [e.scholar]: { ...sd, expenses: newExp } } };
        });
      })
      .subscribe();

    return () => {
      supabase.removeChannel(alertsChannel);
      supabase.removeChannel(actChannel);
      supabase.removeChannel(subChannel);
      supabase.removeChannel(expChannel);
    };
  }, [unlocked]);

  function removeExpenseFromD(scholarKey, expenseId) {
    setD(prev => {
      const sd = prev.scholars[scholarKey];
      if (!sd) return prev;
      const newExp = {};
      Object.entries(sd.expenses || {}).forEach(([sem, list]) => {
        newExp[sem] = list.filter(e => String(e.id) !== String(expenseId));
      });
      return { ...prev, scholars: { ...prev.scholars, [scholarKey]: { ...sd, expenses: newExp } } };
    });
  }

  function addExpenseToD(scholarKey, expense) {
    const sem = expense.sem;
    setD(prev => {
      const sd = prev.scholars[scholarKey];
      if (!sd || !sem) return prev;
      const semList = sd.expenses?.[sem] || [];
      if (semList.some(e => String(e.id) === String(expense.id))) return prev;
      const newExp = { ...(sd.expenses || {}), [sem]: [...semList, expense] };
      return { ...prev, scholars: { ...prev.scholars, [scholarKey]: { ...sd, expenses: newExp } } };
    });
  }

  function updateExpenseInD(scholarKey, expenseId, fields) {
    setD(prev => {
      const sd = prev.scholars[scholarKey];
      if (!sd) return prev;
      const newExp = {};
      Object.entries(sd.expenses || {}).forEach(([sem, list]) => {
        newExp[sem] = list.map(e => String(e.id) === String(expenseId) ? { ...e, ...fields } : e);
      });
      return { ...prev, scholars: { ...prev.scholars, [scholarKey]: { ...sd, expenses: newExp } } };
    });
  }

  async function handleApproveSubmission(sub) {
    try {
      await approveSubmission(sub.id, sub.expense_data, sub.scholar_key);
      setPendingSubmissions(prev => prev.filter(s => s.id !== sub.id));
      if (sub.expense_data) {
        addExpenseToD(sub.scholar_key, { ...sub.expense_data, status: sub.expense_data.avb });
      }
    } catch (err) { console.error('approveSubmission failed:', err); setWriteError(true); }
  }

  async function handleRejectSubmission(sub, comment) {
    try {
      await rejectSubmission(sub.id, comment);
      setPendingSubmissions(prev => prev.filter(s => s.id !== sub.id));
    } catch (err) { console.error('rejectSubmission failed:', err); setWriteError(true); }
  }

  async function handleApproveDelete(item) {
    try {
      await deleteExpense(item.expense_id);
      await markActivityRead([item.id]);
      setActivityFeed(prev => prev.filter(f => f.id !== item.id));
      removeExpenseFromD(item.scholar_key, item.expense_id);
    } catch (err) { console.error('approveDelete failed:', err); }
  }

  async function handleDenyDelete(item) {
    try {
      await markActivityRead([item.id]);
      setActivityFeed(prev => prev.filter(f => f.id !== item.id));
    } catch (err) { console.error('denyDelete failed:', err); }
  }

  async function handleDismissDbAlert(alertId) {
    try {
      await supabase.from('alerts').delete().eq('id', alertId);
      setDbAlerts(prev => prev.filter(a => a.id !== alertId));
    } catch (err) { console.error('dismissAlert failed:', err); }
  }

  async function handleMarkFeedRead(ids) {
    try {
      await markActivityRead(ids);
      setActivityFeed(prev => prev.filter(f => !ids.includes(f.id)));
    } catch (err) { console.error('markRead failed:', err); }
  }

  function handleEditExpense(scholarKey, expenseId, fields) {
    updateExpenseInD(scholarKey, expenseId, fields);
    updateExpense(expenseId, fields).catch(() => setWriteError(true));
  }

  function handleDeleteExpenseFromTable(scholarKey, expenseId) {
    removeExpenseFromD(scholarKey, expenseId);
    setAddedExpenses(prev => ({
      ...prev,
      [scholarKey]: (prev[scholarKey] || []).filter(e => String(e.id) !== String(expenseId)),
    }));
    deleteExpense(expenseId).catch(err => { console.error('deleteExpense failed:', err); setWriteError(true); });
  }

  const [addedExpenses, setAddedExpenses] = useLocalStorage('ngs_added', {});

  const [collapsedSectionsArr, setCollapsedSectionsArr] = useLocalStorage('ngs_collapsed_sections', []);
  const collapsedSections = new Set(collapsedSectionsArr);

  const [fxPanelOpen, setFxPanelOpen] = useLocalStorage('ngs_fx_panel', false);
  const [aiDrawerOpen, setAiDrawerOpen] = useState(false);

  useEffect(() => {
    if (fxMode !== 'market') return;
    setFxStatus('loading');
    fetchMarketRate()
      .then(rate => {
        setFxRate(rate);
        setFxStatus('idle');
        persistFx('market', rate);
      })
      .catch(() => setFxStatus('error'));
  }, [fxMode]);

  function handleFxModeChange(mode) {
    setFxMode(mode);
    if (mode === 'manual') {
      setFxStatus('idle');
      persistFx('manual', fxRate);
    }
  }

  function handleFxRateChange(rate) {
    setFxRate(rate);
    persistFx('manual', rate);
  }

  function handleFxPanelToggle() {
    setFxPanelOpen(v => !v);
  }

  function toggleSection(sectionId) {
    setCollapsedSectionsArr(prev => {
      const set = new Set(prev);
      set.has(sectionId) ? set.delete(sectionId) : set.add(sectionId);
      return [...set];
    });
  }

  function expandAll() {
    setCollapsedSectionsArr([]);
  }

  function collapseAll() {
    setCollapsedSectionsArr(ALL_SECTION_IDS);
  }

  useEffect(() => {
    setSheetsStatus('loading');
    loadFromSupabase()
      .then(data => {
        const hasScholars = data.scholars && Object.keys(data.scholars).length > 0;
        if (!hasScholars) {
          console.warn('Sheets returned no scholar data — using static fallback');
          setSheetsStatus('static');
          return;
        }
        const mergedScholars = {};
        Object.keys(data.scholars).forEach(k => {
          mergedScholars[k] = {
            ...data.scholars[k],
            english: NGS_DATA.scholars[k]?.english,
            publicProfile: NGS_DATA.scholars[k]?.publicProfile,
          };
        });
        const merged = {
          ...data,
          scholars: mergedScholars,
          config: { ...data.config },
        };
        setD(merged);
        setSheetsStatus('live');
      })
      .catch(err => {
        console.warn('Supabase unavailable, using static data:', err.message);
        setSheetsStatus('static');
      });
  }, [refreshKey]);

  function handleAddExpense(scholar, exp) {
    addExpenseToD(scholar, { ...exp, status: exp.avb });
    setAddedExpenses(prev => ({ ...prev, [scholar]: [...(prev[scholar] || []), exp] }));
    writeExpense(scholar, exp).catch(() => setWriteError(true));
  }

  function handleSemesterChange(scholar, sem) {
    writeSemester(scholar, sem);
    setD(prev => ({
      ...prev,
      scholars: {
        ...prev.scholars,
        [scholar]: { ...prev.scholars[scholar], currentSem: sem },
      },
    }));
  }

  function handleGoToIngestion() {
    setAiDrawerOpen(false);
    if (collapsedSections.has('navigator-ai')) toggleSection('navigator-ai');
    setTimeout(() => {
      document.getElementById('sec-navigator-ai')?.scrollIntoView({ behavior: 'smooth' });
    }, 150);
  }

  const sec = (id) => ({
    id: `sec-${id}`,
    collapsed: collapsedSections.has(id),
    onToggle: () => toggleSection(id),
  });

  return (
    <DataCtx.Provider value={{ D, scholarKeys }}>
      <FxCtx.Provider value={fxRate}>
        <LockScreen isHiding={unlocked} onUnlock={() => setUnlocked(true)} />
        <NavBar
          currency={currency}
          onCurrencyChange={setCurrency}
          fxMode={fxMode}
          fxRate={fxRate}
          fxStatus={fxStatus}
          onFxModeChange={handleFxModeChange}
          onFxRateChange={handleFxRateChange}
          sheetsStatus={sheetsStatus}
          onRefresh={() => setRefreshKey(k => k + 1)}
          fxPanelOpen={fxPanelOpen}
          onFxPanelToggle={handleFxPanelToggle}
          onExpandAll={expandAll}
          onCollapseAll={collapseAll}
          aiDrawerOpen={aiDrawerOpen}
          onAiDrawerToggle={() => setAiDrawerOpen(v => !v)}
        />
        <NavigatorAIDrawer
          open={aiDrawerOpen}
          onClose={() => setAiDrawerOpen(false)}
          onGoToIngestion={handleGoToIngestion}
        />
        <main className="wrap">
          <SectionErrorBoundary name="Alerts">
            <AlertsSection
              submissions={pendingSubmissions}
              feed={activityFeed}
              dbAlerts={dbAlerts}
              onApprove={handleApproveSubmission}
              onReject={handleRejectSubmission}
              onApproveDelete={handleApproveDelete}
              onDenyDelete={handleDenyDelete}
              onMarkRead={handleMarkFeedRead}
              onDismissAlert={handleDismissDbAlert}
              {...sec('alerts')}
            />
          </SectionErrorBoundary>
          <SectionErrorBoundary name="Status">
            <StatusSection currency={currency} liveGpa={liveGpa} onSemesterChange={handleSemesterChange} {...sec('status')} />
          </SectionErrorBoundary>
          <SectionErrorBoundary name="Expenses">
            <ExpenseSection
              currency={currency}
              addedExpenses={addedExpenses}
              onAddExpense={handleAddExpense}
              onEditExpense={handleEditExpense}
              onDeleteExpense={handleDeleteExpenseFromTable}
              {...sec('expenses')}
            />
          </SectionErrorBoundary>
          <SectionErrorBoundary name="Deadlines">
            <DeadlinesSection {...sec('deadlines')} />
          </SectionErrorBoundary>
          <SectionErrorBoundary name="English">
            <EnglishSection {...sec('english')} />
          </SectionErrorBoundary>
          <SectionErrorBoundary name="Navigator AI">
            <NavigatorAI {...sec('navigator-ai')} />
          </SectionErrorBoundary>
          <SectionErrorBoundary name="Documents">
            <DocumentsSection {...sec('documents')} />
          </SectionErrorBoundary>
          <SectionErrorBoundary name="Career">
            <CareerSection {...sec('career')} />
          </SectionErrorBoundary>
          <SectionErrorBoundary name="Risk">
            <RiskSection {...sec('risk')} />
          </SectionErrorBoundary>
          <SectionErrorBoundary name="Grades">
            <GradesSection {...sec('grades')} />
          </SectionErrorBoundary>
        </main>
        <NavFooter sheetsStatus={sheetsStatus} writeError={writeError} />
      </FxCtx.Provider>
    </DataCtx.Provider>
  );
}

