import React, { useState, useEffect } from 'react';
import { Routes, Route } from 'react-router-dom';
import { NGS_DATA } from '../../scholars-data.js';
import { useLocalStorage } from '../hooks/useLocalStorage.js';
import { loadFromSupabase, loadPendingSubmissions } from '../supabase-loader.js';
import { writeExpense, writeSemester, updateExpense, deleteExpense, markActivityRead, approveSubmission, rejectSubmission, writeSent } from '../supabase-writer.js';
import { supabase } from '../lib/supabase.js';
import { CAT_TO_BUCKET } from '../constants.js';
import { FxCtx, useFxState } from '../context/FxContext.jsx';
import { DataCtx } from '../context/DataContext.jsx';
import { LockScreen } from '../components/LockScreen.jsx';
import { SectionErrorBoundary } from '../components/SectionErrorBoundary.jsx';
import { NavBar } from '../components/NavBar.jsx';
import { SubmissionBanner } from '../components/expenses/SubmissionBanner.jsx';
import { StatusSection } from '../components/StatusSection.jsx';
import { ExpenseSection } from '../components/expenses/ExpenseSection.jsx';
import { DeadlinesSection } from '../components/DeadlinesSection.jsx';
import { EnglishSection } from '../components/EnglishSection.jsx';
import { NavigatorAI } from '../components/NavigatorAI.jsx';
import { ExpenseWorkbench } from '../components/expenses/ExpenseWorkbench.jsx';
import { NavigatorAIDrawer } from '../components/NavigatorAIDrawer.jsx';
import { MentorHome } from '../components/MentorHome.jsx';
import { DocumentsSection } from '../components/DocumentsSection.jsx';
import { CareerSection } from '../components/CareerSection.jsx';
import { RiskSection } from '../components/RiskSection.jsx';
import { GradesSection } from '../components/GradesSection.jsx';
import { NavFooter } from '../components/NavFooter.jsx';
import { BudgetSection } from '../components/BudgetSection.jsx';
import { TravelModule } from '../components/TravelModule.jsx';
import { MilestonesModule } from '../components/MilestonesModule.jsx';
import { ProgramDetailsSection } from '../components/ProgramDetailsSection.jsx';

if (!NGS_DATA || !NGS_DATA.config) {
  throw new Error('NGS_DATA missing — hard-refresh (Ctrl/Cmd+Shift+R)');
}

const STATIC_SCHOLAR_KEYS = ['claire', 'april', 'janndilyne'];

// Derive the spend bucket for an expense the same way supabase-loader does, so
// realtime INSERT/UPDATE rows get bucketed correctly (not silently → 'college').
function bucketFor(cat, fallback) {
  const raw = CAT_TO_BUCKET[cat] ?? fallback ?? 'college';
  return raw === 'trial' ? 'college' : raw;
}

// Compute per-scholar GPA (as %) from the most recent sem in grade_entries
function computeLiveGpa(rows) {
  const byScholar = {};
  rows.forEach(r => { (byScholar[r.scholar] ??= []).push(r); });
  const result = {};
  Object.entries(byScholar).forEach(([sk, list]) => {
    const sems = [...new Set(list.map(r => r.sem))].sort((a, b) => b.localeCompare(a));
    for (const sem of sems) {
      const semRows = list.filter(r => r.sem === sem && r.pct_equiv != null && r.units);
      if (!semRows.length) continue;
      const totalUnits = semRows.reduce((s, r) => s + r.units, 0);
      if (totalUnits) { result[sk] = semRows.reduce((s, r) => s + r.pct_equiv * r.units, 0) / totalUnits; }
      break;
    }
  });
  return result;
}

export function Navigator() {
  const [D, setD] = useState(NGS_DATA);
  const scholarKeys = STATIC_SCHOLAR_KEYS.filter(k => D.scholars[k]);

  const [unlocked, setUnlocked] = useState(false);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (session) setUnlocked(true);
    });
  }, []);

  // Reactive FX rate (auto-refreshes in market mode), shared with profile pages
  // via localStorage. Replaces a one-time storedRate() read that never updated.
  const { fxRate } = useFxState();
  const [liveGpa, setLiveGpa]   = useState({});
  const [sheetsStatus, setSheetsStatus] = useState('loading');
  const [refreshKey, setRefreshKey]     = useState(0);

  const [writeError, setWriteError] = useState(false);

  // Activity feed — edits/delete requests from entry.html
  const [activityFeed, setActivityFeed] = useState([]);
  // Pending expense submissions awaiting approval
  const [pendingSubmissions, setPendingSubmissions] = useState([]);
  // System alerts from DB (auto-generated by triggers, e.g. GPA risk)
  const [dbAlerts, setDbAlerts] = useState([]);

  useEffect(() => {
    if (!writeError) return;
    const t = setTimeout(() => setWriteError(false), 5000);
    return () => clearTimeout(t);
  }, [writeError]);

  // Load activity + pending submissions on unlock, subscribe to realtime.
  useEffect(() => {
    if (!unlocked) return;

    supabase.from('activity_log').select('*').eq('read', false)
      .order('created_at', { ascending: false })
      .then(({ data }) => setActivityFeed(data || []));

    loadPendingSubmissions()
      .then(setPendingSubmissions)
      .catch(err => console.warn('loadPendingSubmissions failed:', err.message));

    // DB system alerts (GPA risk, etc.)
    supabase.from('alerts').select('*').order('severity')
      .then(({ data }) => setDbAlerts(data || []));

    function reloadAlerts() {
      supabase.from('alerts').select('*').order('severity')
        .then(({ data }) => setDbAlerts(data || []));
    }

    const alertsChannel = supabase.channel('ngs_db_alerts')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'alerts' }, reloadAlerts)
      .subscribe();

    const actChannel = supabase.channel('ngs_activity')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'activity_log' }, payload => {
        setActivityFeed(prev => [payload.new, ...prev]);
      })
      .subscribe();

    const subChannel = supabase.channel('ngs_submissions')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'expense_submissions' }, payload => {
        if (payload.new.status === 'pending') setPendingSubmissions(prev => [payload.new, ...prev]);
      })
      .subscribe();

    // Grade entries → live GPA for status cards
    function reloadLiveGpa() {
      supabase.from('grade_entries').select('scholar,sem,units,pct_equiv')
        .then(({ data }) => { if (data) setLiveGpa(computeLiveGpa(data)); });
    }
    reloadLiveGpa();

    const gradesChannel = supabase.channel('ngs_grade_entries')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'grade_entries' }, reloadLiveGpa)
      .subscribe();

    const expChannel = supabase.channel('ngs_expenses')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'expenses' }, ({ new: e }) => {
        if (!e?.scholar || !e?.sem) return;
        const row = { id: e.id, item: e.item, amount: parseFloat(e.amount) || 0, qty: parseFloat(e.qty) || 1, cat: e.cat, bucket: bucketFor(e.cat, e.bucket), date: e.date, sent: e.sent, avb: e.avb, vendor: e.vendor || '', sem: e.sem, group_id: e.group_id || null };
        setD(prev => {
          const sd = prev.scholars[e.scholar];
          if (!sd) return prev;
          const semList = sd.expenses?.[e.sem] || [];
          if (semList.some(ex => String(ex.id) === String(e.id))) return prev;
          return { ...prev, scholars: { ...prev.scholars, [e.scholar]: { ...sd, expenses: { ...(sd.expenses || {}), [e.sem]: [...semList, row] } } } };
        });
      })
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'expenses' }, ({ new: e }) => {
        if (!e?.scholar) return;
        setD(prev => {
          const sd = prev.scholars[e.scholar];
          if (!sd) return prev;
          const newExp = {};
          Object.entries(sd.expenses || {}).forEach(([sem, list]) => {
            newExp[sem] = list.map(ex => String(ex.id) === String(e.id)
              ? { ...ex, item: e.item, amount: parseFloat(e.amount) || 0, qty: parseFloat(e.qty) || 1, cat: e.cat, bucket: bucketFor(e.cat, e.bucket), date: e.date, sent: e.sent, avb: e.avb, vendor: e.vendor || '', sem: e.sem, group_id: e.group_id || null }
              : ex);
          });
          return { ...prev, scholars: { ...prev.scholars, [e.scholar]: { ...sd, expenses: newExp } } };
        });
      })
      .subscribe();

    return () => {
      supabase.removeChannel(alertsChannel);
      supabase.removeChannel(actChannel);
      supabase.removeChannel(subChannel);
      supabase.removeChannel(gradesChannel);
      supabase.removeChannel(expChannel);
    };
  }, [unlocked]);

  function removeExpenseFromD(scholarKey, expenseId) {
    setD(prev => {
      const sd = prev.scholars[scholarKey];
      if (!sd) return prev;
      const newExp = {};
      Object.entries(sd.expenses || {}).forEach(([sem, list]) => {
        newExp[sem] = list.filter(e => String(e.id) !== String(expenseId));
      });
      return { ...prev, scholars: { ...prev.scholars, [scholarKey]: { ...sd, expenses: newExp } } };
    });
  }

  function addExpenseToD(scholarKey, expense) {
    const sem = expense.sem;
    setD(prev => {
      const sd = prev.scholars[scholarKey];
      if (!sd || !sem) return prev;
      const semList = sd.expenses?.[sem] || [];
      if (semList.some(e => String(e.id) === String(expense.id))) return prev;
      const newExp = { ...(sd.expenses || {}), [sem]: [...semList, expense] };
      return { ...prev, scholars: { ...prev.scholars, [scholarKey]: { ...sd, expenses: newExp } } };
    });
  }

  function updateExpenseInD(scholarKey, expenseId, fields) {
    setD(prev => {
      const sd = prev.scholars[scholarKey];
      if (!sd) return prev;
      const newExp = {};
      Object.entries(sd.expenses || {}).forEach(([sem, list]) => {
        newExp[sem] = list.map(e => String(e.id) === String(expenseId) ? { ...e, ...fields } : e);
      });
      return { ...prev, scholars: { ...prev.scholars, [scholarKey]: { ...sd, expenses: newExp } } };
    });
  }

  async function handleApproveSubmission(sub) {
    try {
      await approveSubmission(sub.id, sub.expense_data, sub.scholar_key);
      setPendingSubmissions(prev => prev.filter(s => s.id !== sub.id));
      if (sub.expense_data) {
        addExpenseToD(sub.scholar_key, { ...sub.expense_data, status: sub.expense_data.avb });
      }
    } catch (err) { console.error('approveSubmission failed:', err); setWriteError(true); }
  }

  async function handleRejectSubmission(sub, comment) {
    try {
      await rejectSubmission(sub.id, comment);
      setPendingSubmissions(prev => prev.filter(s => s.id !== sub.id));
    } catch (err) { console.error('rejectSubmission failed:', err); setWriteError(true); }
  }

  async function handleApproveDelete(item) {
    try {
      await deleteExpense(item.expense_id);
      await markActivityRead([item.id]);
      setActivityFeed(prev => prev.filter(f => f.id !== item.id));
      removeExpenseFromD(item.scholar_key, item.expense_id);
    } catch (err) { console.error('approveDelete failed:', err); }
  }

  async function handleDenyDelete(item) {
    try {
      await markActivityRead([item.id]);
      setActivityFeed(prev => prev.filter(f => f.id !== item.id));
    } catch (err) { console.error('denyDelete failed:', err); }
  }

  async function handleDismissDbAlert(alertId) {
    try {
      await supabase.from('alerts').delete().eq('id', alertId);
      setDbAlerts(prev => prev.filter(a => a.id !== alertId));
    } catch (err) { console.error('dismissAlert failed:', err); }
  }

  async function handleMarkFeedRead(ids) {
    try {
      await markActivityRead(ids);
      setActivityFeed(prev => prev.filter(f => !ids.includes(f.id)));
    } catch (err) { console.error('markRead failed:', err); }
  }

  function handleEditExpense(scholarKey, expenseId, fields) {
    updateExpenseInD(scholarKey, expenseId, fields);
    updateExpense(expenseId, fields).catch(() => setWriteError(true));
  }

  function handleDeleteExpenseFromTable(scholarKey, expenseId) {
    removeExpenseFromD(scholarKey, expenseId);
    setAddedExpenses(prev => ({
      ...prev,
      [scholarKey]: (prev[scholarKey] || []).filter(e => String(e.id) !== String(expenseId)),
    }));
    deleteExpense(expenseId).catch(err => { console.error('deleteExpense failed:', err); setWriteError(true); });
  }

  const [addedExpenses, setAddedExpenses] = useLocalStorage('ngs_added', {});

  const [aiDrawerOpen, setAiDrawerOpen]           = useState(false);
  const [aiDrawerTab, setAiDrawerTab]             = useState('query');
  const [aiDrawerDefaultScholar, setAiDefaultScholar] = useState(null);

  function openDrawer(tab = 'query', scholarKey = null) {
    setAiDrawerTab(tab);
    setAiDefaultScholar(scholarKey);
    setAiDrawerOpen(true);
  }

  useEffect(() => {
    setSheetsStatus('loading');
    loadFromSupabase()
      .then(data => {
        const hasScholars = data.scholars && Object.keys(data.scholars).length > 0;
        if (!hasScholars) {
          console.warn('Sheets returned no scholar data — using static fallback');
          setSheetsStatus('static');
          return;
        }
        const mergedScholars = {};
        Object.keys(data.scholars).forEach(k => {
          mergedScholars[k] = {
            ...data.scholars[k],
            english: NGS_DATA.scholars[k]?.english,
            publicProfile: NGS_DATA.scholars[k]?.publicProfile,
          };
        });
        const merged = {
          ...data,
          scholars: mergedScholars,
          config: { ...data.config },
        };
        setD(merged);
        setSheetsStatus('live');
      })
      .catch(err => {
        console.warn('Supabase unavailable, using static data:', err.message);
        setSheetsStatus('static');
      });
  }, [refreshKey]);

  function handleAddExpense(scholar, exp) {
    addExpenseToD(scholar, { ...exp, status: exp.avb });
    setAddedExpenses(prev => ({ ...prev, [scholar]: [...(prev[scholar] || []), exp] }));
    writeExpense(scholar, exp).catch(() => setWriteError(true));
  }

  // Record a GCash send: insert the transfer fee as a (sent) expense, then mark
  // every item included in the send as sent. Used by the GCash calculator's
  // "Record send" button and its AI box. Returns a summary for the caller's toast.
  function handleRecordSend(scholar, { itemIds = [], fee = 0, sem, feeLabel } = {}) {
    const today = new Date().toISOString().split('T')[0];
    let feeExp = null;
    if (fee > 0) {
      feeExp = {
        id:     `local_${Date.now()}_gcfee`,
        item:   feeLabel || 'GCash fee (transfer)',
        cat:    'Other',
        bucket: CAT_TO_BUCKET['Other'] || 'college',
        amount: fee,
        qty:    1,
        date:   today,
        avb:    'Actual',
        sent:   'Yes',
        sem:    sem || D.scholars[scholar]?.currentSem || '',
      };
      addExpenseToD(scholar, { ...feeExp, status: 'Actual' });
      setAddedExpenses(prev => ({ ...prev, [scholar]: [...(prev[scholar] || []), feeExp] }));
      writeExpense(scholar, feeExp).catch(() => setWriteError(true));
    }
    itemIds.forEach(id => {
      updateExpenseInD(scholar, id, { sent: 'Yes' });
      writeSent(id, scholar).catch(() => setWriteError(true));
    });
    return { feeRecorded: !!feeExp, fee, count: itemIds.length };
  }

  function handleSemesterChange(scholar, sem) {
    writeSemester(scholar, sem);
    setD(prev => ({
      ...prev,
      scholars: {
        ...prev.scholars,
        [scholar]: { ...prev.scholars[scholar], currentSem: sem },
      },
    }));
  }

  return (
    <DataCtx.Provider value={{ D, scholarKeys }}>
      <FxCtx.Provider value={fxRate}>
        <LockScreen isHiding={unlocked} onUnlock={() => setUnlocked(true)} />
        <NavBar
          sheetsStatus={sheetsStatus}
          onRefresh={() => setRefreshKey(k => k + 1)}
          aiDrawerOpen={aiDrawerOpen}
          onAiDrawerToggle={() => setAiDrawerOpen(v => !v)}
        />
        <NavigatorAIDrawer
          open={aiDrawerOpen}
          onClose={() => setAiDrawerOpen(false)}
          tab={aiDrawerTab}
          onTabChange={setAiDrawerTab}
          defaultScholar={aiDrawerDefaultScholar}
        />
        <main className="wrap">
          <Routes>
            <Route index element={
              <SectionErrorBoundary name="MentorHome">
                <MentorHome
                  liveGpa={liveGpa}
                  onOpenDrawer={openDrawer}
                  pendingCount={pendingSubmissions.length}
                  activityCount={activityFeed.length}
                  onSemesterChange={handleSemesterChange}
                />
              </SectionErrorBoundary>
            } />
            <Route path="expenses" element={
              <>
                <SubmissionBanner
                  submissions={pendingSubmissions}
                  feed={activityFeed}
                  dbAlerts={dbAlerts}
                  onApprove={handleApproveSubmission}
                  onReject={handleRejectSubmission}
                  onApproveDelete={handleApproveDelete}
                  onDenyDelete={handleDenyDelete}
                  onMarkRead={handleMarkFeedRead}
                  onDismissAlert={handleDismissDbAlert}
                />
                <SectionErrorBoundary name="Expenses">
                  <ExpenseSection
                    currency="PHP"
                    addedExpenses={addedExpenses}
                    onAddExpense={handleAddExpense}
                    onEditExpense={handleEditExpense}
                    onDeleteExpense={handleDeleteExpenseFromTable}
                    id="sec-expenses" collapsed={false} onToggle={() => {}}
                    workbenchSlot={scholar => (
                      <ExpenseWorkbench
                        scholar={scholar}
                        onAddExpense={handleAddExpense}
                        onRecordSend={handleRecordSend}
                      />
                    )}
                  />
                </SectionErrorBoundary>
              </>
            } />
            <Route path="grades" element={
              <SectionErrorBoundary name="Grades">
                <GradesSection id="sec-grades" collapsed={false} onToggle={() => {}} />
              </SectionErrorBoundary>
            } />
            <Route path="english" element={
              <>
                <SectionErrorBoundary name="English">
                  <EnglishSection id="sec-english" collapsed={false} onToggle={() => {}} />
                </SectionErrorBoundary>
                <SectionErrorBoundary name="Navigator AI">
                  <NavigatorAI id="sec-navigator-ai" collapsed={false} onToggle={() => {}} englishOnly={true} />
                </SectionErrorBoundary>
              </>
            } />
            <Route path="deadlines" element={
              <SectionErrorBoundary name="Deadlines">
                <DeadlinesSection id="sec-deadlines" collapsed={false} onToggle={() => {}} />
              </SectionErrorBoundary>
            } />
            <Route path="progress" element={
              <>
                <SectionErrorBoundary name="Career">
                  <CareerSection id="sec-career" collapsed={false} onToggle={() => {}} />
                </SectionErrorBoundary>
                <SectionErrorBoundary name="Risk">
                  <RiskSection id="sec-risk" collapsed={false} onToggle={() => {}} />
                </SectionErrorBoundary>
              </>
            } />
            <Route path="docs" element={
              <SectionErrorBoundary name="Documents">
                <DocumentsSection id="sec-documents" collapsed={false} onToggle={() => {}} />
              </SectionErrorBoundary>
            } />
            <Route path="budget" element={
              <SectionErrorBoundary name="Budget">
                <BudgetSection />
              </SectionErrorBoundary>
            } />
            <Route path="program-details" element={
              <SectionErrorBoundary name="Program Details">
                <ProgramDetailsSection id="sec-program-details" collapsed={false} onToggle={() => {}} />
              </SectionErrorBoundary>
            } />
            <Route path="travel" element={
              <SectionErrorBoundary name="Travel">
                <TravelModule id="sec-travel" />
              </SectionErrorBoundary>
            } />
            <Route path="milestones" element={
              <SectionErrorBoundary name="Milestones">
                <MilestonesModule id="sec-milestones" />
              </SectionErrorBoundary>
            } />
          </Routes>
        </main>
        {unlocked && !aiDrawerOpen && (
          <button
            className="nav-ai-fab"
            onClick={() => openDrawer('query')}
            title="Ask the Navigator AI"
          >
            <span className="nav-ai-fab-dot" />
            Ask AI
          </button>
        )}
        <NavFooter sheetsStatus={sheetsStatus} writeError={writeError} />
      </FxCtx.Provider>
    </DataCtx.Provider>
  );
}

